server:
  port: 8082
spring:
  application:
    name: ddd-product
  kafka:
    bootstrap-servers: ec2-34-219-190-76.us-west-2.compute.amazonaws.com:9092
    consumer:
      group-id: product
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit:  false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      transaction-id-prefix: sales_error
      properties:
        enable:
          idempotence: true
        transactional:
          id: sales_error
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle
    driverClassName: org.h2.Driver
    username: qualidade

  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
app:
  topic: sales
  topicError: sales_error